"""test_delete_alembic_version

Revision ID: 998998040d9d
Revises: 0fda3d675c2b
Create Date: 2020-09-22 11:07:14.745274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998998040d9d'
down_revision = '0fda3d675c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktail',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cocktail_desc'), 'cocktail', ['desc'], unique=False)
    op.create_index(op.f('ix_cocktail_name'), 'cocktail', ['name'], unique=True)
    op.create_index(op.f('ix_cocktail_picture'), 'cocktail', ['picture'], unique=True)
    op.create_index(op.f('ix_cocktail_timestamp'), 'cocktail', ['timestamp'], unique=False)
    op.drop_index('ix_recipe_desc', table_name='recipe')
    op.drop_index('ix_recipe_name', table_name='recipe')
    op.drop_index('ix_recipe_picture', table_name='recipe')
    op.drop_index('ix_recipe_timestamp', table_name='recipe')
    op.drop_table('recipe')
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'cocktail', ['cocktail_key'], ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipe', ['cocktail_key'], ['key'])
    op.create_table('recipe',
    sa.Column('key', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=400), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_recipe_timestamp', 'recipe', ['timestamp'], unique=False)
    op.create_index('ix_recipe_picture', 'recipe', ['picture'], unique=1)
    op.create_index('ix_recipe_name', 'recipe', ['name'], unique=1)
    op.create_index('ix_recipe_desc', 'recipe', ['desc'], unique=False)
    op.drop_index(op.f('ix_cocktail_timestamp'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_picture'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_name'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_desc'), table_name='cocktail')
    op.drop_table('cocktail')
    # ### end Alembic commands ###
