"""user, cocktailö and ingredient

Revision ID: aacc36dde219
Revises: 
Create Date: 2020-04-09 21:16:48.290857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacc36dde219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cocktail',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=180), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cocktail_desc'), 'cocktail', ['desc'], unique=False)
    op.create_index(op.f('ix_cocktail_name'), 'cocktail', ['name'], unique=True)
    op.create_table('ingredient',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('cocktail_key', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_key'], ['cocktail.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=False)
    op.create_index(op.f('ix_ingredient_quantity'), 'ingredient', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_quantity'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_cocktail_name'), table_name='cocktail')
    op.drop_index(op.f('ix_cocktail_desc'), table_name='cocktail')
    op.drop_table('cocktail')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
