"""Initial migration

Revision ID: db5940de2a01
Revises: 
Create Date: 2020-09-22 15:11:01.145398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5940de2a01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recipe',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.String(length=125), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_recipe_desc'), 'recipe', ['desc'], unique=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=True)
    op.create_index(op.f('ix_recipe_picture'), 'recipe', ['picture'], unique=True)
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    op.create_table('ingredient',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('recipe_key', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['recipe_key'], ['recipe.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=False)
    op.create_index(op.f('ix_ingredient_quantity'), 'ingredient', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_quantity'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_picture'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_desc'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
